#!/bin/bash

WALLPAPER_DIR="$HOME/Imagens/wallpapers"
FUZZEL_CMD="fuzzel --dmenu"

generate_fuzzel_list() {
  find "$WALLPAPER_DIR" -type f \
    \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" \) \
    -printf '%f\n' | sort -u
}

set_wallpaper() {
  local wallpaper_path="$1"
  [ -z "$wallpaper_path" ] && return 1

ln -sfn "$wallpaper_path" "$HOME/.config/niri/current_wallpaper"

swww img "$wallpaper_path" --transition-type wipe --transition-angle 60

notify-send "Wallpaper alterado" "$(basename "$wallpaper_path")"
}

chosen_filename=$(generate_fuzzel_list | $FUZZEL_CMD)
[ -z "$chosen_filename" ] && exit 0

full_path=$(find "$WALLPAPER_DIR" -type f -name "$chosen_filename" | head -n 1)

set_wallpaper "$full_path"
