source = ~/.config/hypr/colors.conf

background {
    monitor =
    color = $color
    path =  /home/tux/Imagens/wallpapers/Sans frisk.png
    blur_passes = 2
}

animations {
    enabled = true
}

input-field {
    size = 300, 80
    position = 0, -10
    halign = center
    valign = center

    inner_color = $background
    outer_color = $outline
    outline_thickness = 1

    font_family = Jetbrains Mono Nerd Font
    font_color = rgba(ebebebff)

    placeholder_text = Enter password 
    check_color = $check_color
    fail_text = <i>Wrong passowrd [$ATTEMPTS] </i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

label {
    monitor =
    text = cmd[update:1000] date "+<b><big>%H</big></b>"
    color = rgb(255, 255, 255)
    font_size = 100
    font_family = Orbitron
    position = -100, 100
    halign = center
    valign = center
}

# Minutos (MM)
label {
    monitor =
    text = cmd[update:1000] date "+<b><big>%M</big></b>"
    color = rgb(255, 255, 255)
    font_size = 100
    font_family = Orbitron
    position = 100, 100
    halign = center
    valign = center
}
auth {
    fingerprint:enabled = true
}
